### PR TITLE
Do not add `undefined` params in the URL and default to `{}` for params

### PR DESCRIPTION
**Pull request by dmatteo**
This PR fixes an issue that occurs when the generated code has expansion parameters and none are passed in. Undefined params are now filtered out when building the query object.

E.g.
```js
    GetInfo(params) {
      let headers = {

      };
      return fetch(endpoint + basePath + '/service/api/v1/info' + '?' + buildQuery({
          '$top': params['$top'],
          '$skip': params['$skip'],
        })

        , {
          method: 'GET',
          headers,
          mode,
        });
    },
```

When called with an empty object, it will generate an URL like

```
http://something.com/service/api/v1/info?&&
```

---

The second commit simply allows the methods to be called without params, instead of always requiring an empty object to be passed in

---

I can split into 2 PRs, if you like, but they're loosely related

### CODE REVIEW

**Comment by dmatteo** [comment]
This will not be natively compatible with Node < 6.4, since the ES6 default value has been introduced in that release.

I suggest you publish this with a new major version, or we can compile everything with babel and have it retro compatible to older Node versions

**Comment by jsdevel** [comment]
Is there a way to avoid using `>= 6.4` ES6 features @dmatteo ?  I'd rather avoid babel as it adds a lot more cruft.

**Comment by jsdevel** [comment]
Also, if the generated output would introduce breaking changes, then I would definitely prefer to avoid that.

**Comment by dmatteo** [comment]
@jsdevel I understand your reluctance in breaking off older Node version, and I can fix that with babel. I'm not sure what do you mean by "adding too much cruft" though.

It's just adding a couple of dev dependencies and then add a compile step before publishing the module.

I'll update the PR tomorrow with those changes, and then if you still don't feel like introducing those changes I guess I'll just fork the repo.

Thanks!

**Comment by jsdevel** [comment]
@dmatteo no need to fork.  We'll get your changes in.  My only real concern was ensuring it's backwards compatible.  Being that it's also a CLI tool back compat is crucial.

I don't mind adding babel, but I also don't see much of a need if we just avoid the features that would require it.  Is it needed?

**Comment by dmatteo** [comment]
I think it's a bit silly that I have to call a method with an empty object, if I don't need to pass any option inside a method, and that's why I've added the default to `{}`.

Now, that could also be achieved by checking `params` inside the method, instead of using ES6 default value, but it seems going backwards to me, since we have native support for it.

What do you think?

**Comment by jsdevel** [comment]
> I think it's a bit silly that I have to call a method with an empty object, if I don't need to pass any option inside a method, and that's why I've added the default to {}.

I agree completely that you shouldn't have to call the method with params.  They should be optional if none were defined.

> Now, that could also be achieved by checking params inside the method, instead of using ES6 default value, but it seems going backwards to me, since we have native support for it.

We have native support for it in recent versions of node (as you said before).  The question is whether or not the effort of adding babel to support default values is worth it.


I'm not opposed to adding babel if you'd prefer to see this library go that route; however, I see `if (!params) params = {};` as an easier to maintain solution given that this is a rather simple and straightforward CLI tool.  If this project were huge then I'd totally be on board with babel.  I'm not sure the returns are worth it though for this project.

Either way, I'm thankful that you've opened this PR and I'd love to see it get merged!

**Comment by dmatteo** [comment]
Yeah, I see what you mean. I personally find babel _enjoyable_, if you wish, but it might be a bit of a barrier for people not used to it.

I don't have a problem checking if `params` is undefined, although I would rather check for type undefined (`typeof params === 'undefined'`), to avoid taking in null values as well (which may have different values in some APIs).

I'll get it done

**Comment by dmatteo** [comment]
@jsdevel thoughts?

**Comment by jsdevel** [comment]
Looks good!  I like the `undefined` check.  Thank you so much!

**Comment by jsdevel** [comment]
published as `v0.6.0`

**Comment by dmatteo** [comment]
Thank you for your quick interactions 👍

**Pull request merged**
